/**
 * AI Model Catalog - November 2025
 * Complete catalog of supported AI models with latest offerings
 */

export interface AIModel {
  id: string;
  name: string;
  provider: string;
  icon: string;
  description: string;
  contextWindow: number;
  inputCost: number; // per million tokens
  outputCost: number; // per million tokens
  features: string[];
  apiEndpoint?: string;
  category: 'flagship' | 'fast' | 'efficient' | 'specialized' | 'reasoning' | 'legacy';
  releaseDate: string;
  maxOutput?: number;
  supportsStreaming?: boolean;
}

export const AI_MODELS: AIModel[] = [
  // ==========================================
  // OpenAI GPT-5.x Family
  // ==========================================
  {
    id: 'gpt-5.1',
    name: 'GPT-5.1',
    provider: 'OpenAI',
    icon: '◎',
    description: 'Latest GPT-5 with enhanced capabilities',
    contextWindow: 300000,
    inputCost: 1.5,
    outputCost: 12,
    maxOutput: 150000,
    features: ['reasoning', 'multimodal', 'coding', 'analysis'],
    category: 'flagship',
    releaseDate: '2025-05',
    supportsStreaming: true,
  },
  {
    id: 'gpt-5.1-chat-latest',
    name: 'GPT-5.1 Chat Latest',
    provider: 'OpenAI',
    icon: '◎',
    description: 'Always points to latest GPT-5.1 snapshot',
    contextWindow: 300000,
    inputCost: 1.5,
    outputCost: 12,
    maxOutput: 150000,
    features: ['reasoning', 'multimodal', 'chat-optimized'],
    category: 'flagship',
    releaseDate: '2025-05',
    supportsStreaming: true,
  },
  {
    id: 'gpt-5.1-codex',
    name: 'GPT-5.1 Codex',
    provider: 'OpenAI',
    icon: '◐',
    description: 'Specialized for code generation and analysis',
    contextWindow: 300000,
    inputCost: 1.8,
    outputCost: 14,
    maxOutput: 150000,
    features: ['coding', 'debugging', 'code-analysis', 'refactoring'],
    category: 'specialized',
    releaseDate: '2025-05',
    supportsStreaming: true,
  },
  {
    id: 'gpt-5.1-codex-mini',
    name: 'GPT-5.1 Codex Mini',
    provider: 'OpenAI',
    icon: '◑',
    description: 'Efficient code model for rapid development',
    contextWindow: 150000,
    inputCost: 0.8,
    outputCost: 6,
    maxOutput: 75000,
    features: ['coding', 'fast', 'efficient'],
    category: 'efficient',
    releaseDate: '2025-05',
    supportsStreaming: true,
  },
  {
    id: 'gpt-5',
    name: 'GPT-5',
    provider: 'OpenAI',
    icon: '◉',
    description: 'Powerful reasoning with minimal hallucinations',
    contextWindow: 272000,
    inputCost: 1.25,
    outputCost: 10,
    maxOutput: 128000,
    features: ['reasoning', 'multimodal', 'analysis'],
    category: 'flagship',
    releaseDate: '2025-03',
    supportsStreaming: true,
  },
  {
    id: 'gpt-5-mini',
    name: 'GPT-5 Mini',
    provider: 'OpenAI',
    icon: '○',
    description: 'Balanced GPT-5 for cost efficiency',
    contextWindow: 150000,
    inputCost: 0.5,
    outputCost: 5,
    maxOutput: 64000,
    features: ['reasoning', 'efficient', 'fast'],
    category: 'efficient',
    releaseDate: '2025-03',
    supportsStreaming: true,
  },
  {
    id: 'gpt-5-nano',
    name: 'GPT-5 Nano',
    provider: 'OpenAI',
    icon: '·',
    description: 'Lightweight GPT-5 for edge deployment',
    contextWindow: 100000,
    inputCost: 0.25,
    outputCost: 2.5,
    maxOutput: 32000,
    features: ['fast', 'edge', 'lightweight'],
    category: 'fast',
    releaseDate: '2025-03',
    supportsStreaming: true,
  },
  {
    id: 'gpt-5-chat-latest',
    name: 'GPT-5 Chat Latest',
    provider: 'OpenAI',
    icon: '◉',
    description: 'Latest GPT-5 chat snapshot',
    contextWindow: 272000,
    inputCost: 1.25,
    outputCost: 10,
    maxOutput: 128000,
    features: ['chat', 'reasoning', 'multimodal'],
    category: 'flagship',
    releaseDate: '2025-03',
    supportsStreaming: true,
  },

  // ==========================================
  // OpenAI GPT-4.x Family
  // ==========================================
  {
    id: 'gpt-4.1',
    name: 'GPT-4.1',
    provider: 'OpenAI',
    icon: '⊙',
    description: 'Enhanced GPT-4 with improved capabilities',
    contextWindow: 128000,
    inputCost: 0.8,
    outputCost: 6,
    maxOutput: 64000,
    features: ['reasoning', 'coding', 'multimodal'],
    category: 'efficient',
    releaseDate: '2025-01',
    supportsStreaming: true,
  },
  {
    id: 'gpt-4.1-mini',
    name: 'GPT-4.1 Mini',
    provider: 'OpenAI',
    icon: '◦',
    description: 'Compact GPT-4.1 for efficiency',
    contextWindow: 64000,
    inputCost: 0.4,
    outputCost: 3,
    maxOutput: 32000,
    features: ['efficient', 'fast', 'coding'],
    category: 'efficient',
    releaseDate: '2025-01',
    supportsStreaming: true,
  },
  {
    id: 'gpt-4.1-nano',
    name: 'GPT-4.1 Nano',
    provider: 'OpenAI',
    icon: '•',
    description: 'Ultralight GPT-4.1',
    contextWindow: 32000,
    inputCost: 0.2,
    outputCost: 1.5,
    maxOutput: 16000,
    features: ['fast', 'lightweight'],
    category: 'fast',
    releaseDate: '2025-01',
    supportsStreaming: true,
  },
  {
    id: 'gpt-4o',
    name: 'GPT-4o',
    provider: 'OpenAI',
    icon: '⊕',
    description: 'Optimized for real-time multimodal tasks',
    contextWindow: 128000,
    inputCost: 2.5,
    outputCost: 10,
    maxOutput: 16384,
    features: ['multimodal', 'realtime', 'vision', 'audio'],
    category: 'specialized',
    releaseDate: '2024-05',
    supportsStreaming: true,
  },
  {
    id: 'gpt-4o-mini',
    name: 'GPT-4o Mini',
    provider: 'OpenAI',
    icon: '⊖',
    description: 'Efficient multimodal model',
    contextWindow: 128000,
    inputCost: 0.15,
    outputCost: 0.6,
    maxOutput: 16384,
    features: ['multimodal', 'efficient', 'fast'],
    category: 'efficient',
    releaseDate: '2024-07',
    supportsStreaming: true,
  },
  {
    id: 'gpt-4',
    name: 'GPT-4',
    provider: 'OpenAI',
    icon: '⊗',
    description: 'Original GPT-4 model',
    contextWindow: 8192,
    inputCost: 30,
    outputCost: 60,
    maxOutput: 8192,
    features: ['reasoning', 'coding'],
    category: 'legacy',
    releaseDate: '2023-03',
    supportsStreaming: true,
  },
  {
    id: 'gpt-4-turbo',
    name: 'GPT-4 Turbo',
    provider: 'OpenAI',
    icon: '⊘',
    description: 'GPT-4 with improved speed and knowledge',
    contextWindow: 128000,
    inputCost: 10,
    outputCost: 30,
    maxOutput: 4096,
    features: ['reasoning', 'vision', 'json-mode'],
    category: 'efficient',
    releaseDate: '2024-04',
    supportsStreaming: true,
  },

  // ==========================================
  // OpenAI GPT-3.x (Legacy)
  // ==========================================
  {
    id: 'gpt-3.5-turbo',
    name: 'GPT-3.5 Turbo',
    provider: 'OpenAI',
    icon: '⊝',
    description: 'Fast, efficient legacy model',
    contextWindow: 16385,
    inputCost: 0.5,
    outputCost: 1.5,
    maxOutput: 4096,
    features: ['chat', 'fast', 'json-mode'],
    category: 'legacy',
    releaseDate: '2022-11',
    supportsStreaming: true,
  },

  // ==========================================
  // OpenAI O-Series (Reasoning Models)
  // ==========================================
  {
    id: 'o4-mini',
    name: 'O4 Mini',
    provider: 'OpenAI',
    icon: '◈',
    description: 'Latest efficient reasoning model',
    contextWindow: 128000,
    inputCost: 3,
    outputCost: 12,
    maxOutput: 65536,
    features: ['reasoning', 'chain-of-thought', 'verification'],
    category: 'reasoning',
    releaseDate: '2025-10',
    supportsStreaming: false,
  },
  {
    id: 'o3',
    name: 'O3',
    provider: 'OpenAI',
    icon: '◊',
    description: 'Advanced reasoning with deep analysis',
    contextWindow: 128000,
    inputCost: 8,
    outputCost: 32,
    maxOutput: 100000,
    features: ['reasoning', 'deep-analysis', 'math', 'science'],
    category: 'reasoning',
    releaseDate: '2025-08',
    supportsStreaming: false,
  },
  {
    id: 'o3-pro',
    name: 'O3 Pro',
    provider: 'OpenAI',
    icon: '◆',
    description: 'Maximum reasoning capability',
    contextWindow: 128000,
    inputCost: 15,
    outputCost: 60,
    maxOutput: 100000,
    features: ['reasoning', 'research', 'complex-math', 'verification'],
    category: 'reasoning',
    releaseDate: '2025-08',
    supportsStreaming: false,
  },
  {
    id: 'o3-mini',
    name: 'O3 Mini',
    provider: 'OpenAI',
    icon: '◇',
    description: 'Efficient O3 reasoning',
    contextWindow: 128000,
    inputCost: 4,
    outputCost: 16,
    maxOutput: 65536,
    features: ['reasoning', 'efficient', 'verification'],
    category: 'reasoning',
    releaseDate: '2025-08',
    supportsStreaming: false,
  },
  {
    id: 'o1',
    name: 'O1',
    provider: 'OpenAI',
    icon: '⬢',
    description: 'Original reasoning model',
    contextWindow: 128000,
    inputCost: 15,
    outputCost: 60,
    maxOutput: 32768,
    features: ['reasoning', 'chain-of-thought'],
    category: 'reasoning',
    releaseDate: '2024-09',
    supportsStreaming: false,
  },
  {
    id: 'o1-mini',
    name: 'O1 Mini',
    provider: 'OpenAI',
    icon: '⬡',
    description: 'Fast reasoning for STEM',
    contextWindow: 128000,
    inputCost: 3,
    outputCost: 12,
    maxOutput: 65536,
    features: ['reasoning', 'math', 'coding', 'fast'],
    category: 'reasoning',
    releaseDate: '2024-09',
    supportsStreaming: false,
  },

  // ==========================================
  // Anthropic Claude Family
  // ==========================================
  {
    id: 'claude-sonnet-4-5',
    name: 'Claude Sonnet 4.5',
    provider: 'Anthropic',
    icon: '◉',
    description: 'Balanced intelligence and speed',
    contextWindow: 200000,
    inputCost: 3,
    outputCost: 15,
    maxOutput: 8192,
    features: ['coding', 'vision', 'analysis', 'enterprise'],
    category: 'flagship',
    releaseDate: '2025-09',
    supportsStreaming: true,
  },
  {
    id: 'claude-sonnet-4-5-20250929',
    name: 'Claude Sonnet 4.5 (Sept 2025)',
    provider: 'Anthropic',
    icon: '◉',
    description: 'Specific September snapshot',
    contextWindow: 200000,
    inputCost: 3,
    outputCost: 15,
    maxOutput: 8192,
    features: ['coding', 'vision', 'analysis'],
    category: 'flagship',
    releaseDate: '2025-09',
    supportsStreaming: true,
  },
  {
    id: 'claude-haiku-4-5',
    name: 'Claude Haiku 4.5',
    provider: 'Anthropic',
    icon: '○',
    description: 'Fast, efficient Claude',
    contextWindow: 200000,
    inputCost: 0.25,
    outputCost: 1.25,
    maxOutput: 8192,
    features: ['fast', 'efficient', 'chat'],
    category: 'fast',
    releaseDate: '2025-10',
    supportsStreaming: true,
  },
  {
    id: 'claude-haiku-4-5-20251001',
    name: 'Claude Haiku 4.5 (Oct 2025)',
    provider: 'Anthropic',
    icon: '○',
    description: 'Specific October snapshot',
    contextWindow: 200000,
    inputCost: 0.25,
    outputCost: 1.25,
    maxOutput: 8192,
    features: ['fast', 'efficient'],
    category: 'fast',
    releaseDate: '2025-10',
    supportsStreaming: true,
  },
  {
    id: 'claude-opus-4-1',
    name: 'Claude Opus 4.1',
    provider: 'Anthropic',
    icon: '◆',
    description: 'Most intelligent Claude model',
    contextWindow: 200000,
    inputCost: 15,
    outputCost: 75,
    maxOutput: 4096,
    features: ['reasoning', 'analysis', 'creative', 'research'],
    category: 'flagship',
    releaseDate: '2025-08',
    supportsStreaming: true,
  },
  {
    id: 'claude-opus-4-1-20250805',
    name: 'Claude Opus 4.1 (Aug 2025)',
    provider: 'Anthropic',
    icon: '◆',
    description: 'Specific August snapshot',
    contextWindow: 200000,
    inputCost: 15,
    outputCost: 75,
    maxOutput: 4096,
    features: ['reasoning', 'analysis', 'creative'],
    category: 'flagship',
    releaseDate: '2025-08',
    supportsStreaming: true,
  },

  // ==========================================
  // Google Gemini 2.5 Family
  // ==========================================
  {
    id: 'gemini-2.5-pro',
    name: 'Gemini 2.5 Pro',
    provider: 'Google',
    icon: '◈',
    description: 'Most capable Gemini with thinking mode',
    contextWindow: 1000000,
    inputCost: 0.15,
    outputCost: 3,
    maxOutput: 8192,
    features: ['thinking', 'multimodal', 'long-context', 'tools'],
    category: 'flagship',
    releaseDate: '2025-09',
    supportsStreaming: true,
  },
  {
    id: 'gemini-2.5-flash',
    name: 'Gemini 2.5 Flash',
    provider: 'Google',
    icon: '◇',
    description: 'Fast with thinking capabilities',
    contextWindow: 1000000,
    inputCost: 0.075,
    outputCost: 0.3,
    maxOutput: 8192,
    features: ['fast', 'thinking', 'multimodal', 'efficient'],
    category: 'efficient',
    releaseDate: '2025-09',
    supportsStreaming: true,
  },
  {
    id: 'gemini-2.5-flash-lite',
    name: 'Gemini 2.5 Flash-Lite',
    provider: 'Google',
    icon: '◦',
    description: 'Ultra-fast and cost-efficient',
    contextWindow: 1000000,
    inputCost: 0.05,
    outputCost: 0.15,
    maxOutput: 8192,
    features: ['ultrafast', 'edge', 'efficient'],
    category: 'fast',
    releaseDate: '2025-09',
    supportsStreaming: true,
  },
  {
    id: 'gemini-2.0-flash',
    name: 'Gemini 2.0 Flash',
    provider: 'Google',
    icon: '◊',
    description: 'Stable with native tool use',
    contextWindow: 1000000,
    inputCost: 0.075,
    outputCost: 0.3,
    maxOutput: 8192,
    features: ['tools', 'multimodal', 'stable'],
    category: 'efficient',
    releaseDate: '2025-02',
    supportsStreaming: true,
  },
  {
    id: 'gemini-2.0-flash-lite',
    name: 'Gemini 2.0 Flash-Lite',
    provider: 'Google',
    icon: '·',
    description: 'Lightweight stable model',
    contextWindow: 1000000,
    inputCost: 0.05,
    outputCost: 0.15,
    maxOutput: 8192,
    features: ['fast', 'stable', 'lightweight'],
    category: 'fast',
    releaseDate: '2025-02',
    supportsStreaming: true,
  },

  // ==========================================
  // Moonshot AI / Kimi Family
  // ==========================================
  {
    id: 'kimi-k2',
    name: 'Kimi K2',
    provider: 'Moonshot',
    icon: '⬟',
    description: 'Base K2 frontier model',
    contextWindow: 256000,
    inputCost: 0.15,
    outputCost: 2.5,
    maxOutput: 8192,
    features: ['reasoning', 'tools', 'coding'],
    category: 'flagship',
    releaseDate: '2025-09',
    supportsStreaming: true,
  },
  {
    id: 'kimi-k2-0905-preview',
    name: 'Kimi K2 (Sept Preview)',
    provider: 'Moonshot',
    icon: '⬟',
    description: '256K context, upgraded coding & tools',
    contextWindow: 256000,
    inputCost: 0.15,
    outputCost: 2.5,
    maxOutput: 8192,
    features: ['coding', 'tools', 'reasoning'],
    category: 'flagship',
    releaseDate: '2025-09',
    supportsStreaming: true,
  },
  {
    id: 'kimi-k2-0711-preview',
    name: 'Kimi K2 (July Preview)',
    provider: 'Moonshot',
    icon: '⬟',
    description: 'Earlier K2 snapshot',
    contextWindow: 256000,
    inputCost: 0.15,
    outputCost: 2.5,
    maxOutput: 8192,
    features: ['reasoning', 'tools'],
    category: 'flagship',
    releaseDate: '2025-07',
    supportsStreaming: true,
  },
  {
    id: 'kimi-k2-turbo-preview',
    name: 'Kimi K2 Turbo',
    provider: 'Moonshot',
    icon: '○',
    description: 'High-throughput K2',
    contextWindow: 256000,
    inputCost: 0.1,
    outputCost: 2,
    maxOutput: 8192,
    features: ['fast', 'efficient', 'tools'],
    category: 'efficient',
    releaseDate: '2025-09',
    supportsStreaming: true,
  },
  {
    id: 'kimi-k2-thinking',
    name: 'Kimi K2 Thinking',
    provider: 'Moonshot',
    icon: '◈',
    description: 'Multi-step reasoning version',
    contextWindow: 256000,
    inputCost: 0.2,
    outputCost: 3,
    maxOutput: 16384,
    features: ['thinking', 'reasoning', 'chain-of-thought'],
    category: 'reasoning',
    releaseDate: '2025-10',
    supportsStreaming: true,
  },
  {
    id: 'moonshot-v1',
    name: 'Moonshot v1',
    provider: 'Moonshot',
    icon: '◦',
    description: 'Original large model',
    contextWindow: 128000,
    inputCost: 0.12,
    outputCost: 2,
    maxOutput: 8192,
    features: ['general', 'stable'],
    category: 'legacy',
    releaseDate: '2024-04',
    supportsStreaming: true,
  },
  {
    id: 'moonshot-v1-8k',
    name: 'Moonshot v1-8K',
    provider: 'Moonshot',
    icon: '·',
    description: '8K context window',
    contextWindow: 8000,
    inputCost: 0.08,
    outputCost: 1.5,
    maxOutput: 4096,
    features: ['general', 'short-context'],
    category: 'legacy',
    releaseDate: '2024-04',
    supportsStreaming: true,
  },
  {
    id: 'moonshot-v1-32k',
    name: 'Moonshot v1-32K',
    provider: 'Moonshot',
    icon: '•',
    description: '32K context window',
    contextWindow: 32000,
    inputCost: 0.1,
    outputCost: 1.8,
    maxOutput: 8192,
    features: ['general', 'medium-context'],
    category: 'legacy',
    releaseDate: '2024-04',
    supportsStreaming: true,
  },

  // ==========================================
  // DeepSeek Family
  // ==========================================
  {
    id: 'deepseek-chat',
    name: 'DeepSeek Chat',
    provider: 'DeepSeek',
    icon: '◉',
    description: 'DeepSeek-V3.2-Exp (non-thinking)',
    contextWindow: 64000,
    inputCost: 0.14,
    outputCost: 2.8,
    maxOutput: 8192,
    features: ['chat', 'coding', 'general'],
    category: 'efficient',
    releaseDate: '2025-11',
    supportsStreaming: true,
  },
  {
    id: 'deepseek-reasoner',
    name: 'DeepSeek Reasoner',
    provider: 'DeepSeek',
    icon: '◈',
    description: 'DeepSeek-V3.2-Exp with DeepThink',
    contextWindow: 64000,
    inputCost: 0.55,
    outputCost: 2.19,
    maxOutput: 8192,
    features: ['reasoning', 'chain-of-thought', 'verification'],
    category: 'reasoning',
    releaseDate: '2025-11',
    supportsStreaming: true,
  },

  // ==========================================
  // Meta Llama Family
  // ==========================================
  {
    id: 'llama-4-scout',
    name: 'Llama 4 Scout',
    provider: 'Meta',
    icon: '◆',
    description: 'Multimodal with 10M context',
    contextWindow: 10000000,
    inputCost: 0.2,
    outputCost: 3,
    maxOutput: 8192,
    features: ['multimodal', 'ultra-long-context', 'moe'],
    category: 'flagship',
    releaseDate: '2025-07',
    supportsStreaming: true,
  },
  {
    id: 'llama-3.3-70b',
    name: 'Llama 3.3 70B',
    provider: 'Meta',
    icon: '◇',
    description: 'High-quality text generation',
    contextWindow: 128000,
    inputCost: 0.1,
    outputCost: 1.5,
    maxOutput: 8192,
    features: ['text', 'efficient', 'multilingual'],
    category: 'efficient',
    releaseDate: '2025-05',
    supportsStreaming: true,
  },
  {
    id: 'llama-3.2-90b-vision',
    name: 'Llama 3.2 90B Vision',
    provider: 'Meta',
    icon: '◈',
    description: 'Multimodal vision model',
    contextWindow: 128000,
    inputCost: 0.3,
    outputCost: 4,
    maxOutput: 8192,
    features: ['vision', 'multimodal', 'image-understanding'],
    category: 'specialized',
    releaseDate: '2024-09',
    supportsStreaming: true,
  },
  {
    id: 'llama-3.2-11b',
    name: 'Llama 3.2 11B',
    provider: 'Meta',
    icon: '○',
    description: 'Lightweight multimodal',
    contextWindow: 128000,
    inputCost: 0.055,
    outputCost: 0.7,
    maxOutput: 8192,
    features: ['multimodal', 'efficient', 'vision'],
    category: 'efficient',
    releaseDate: '2024-09',
    supportsStreaming: true,
  },
  {
    id: 'llama-3.2-3b',
    name: 'Llama 3.2 3B',
    provider: 'Meta',
    icon: '·',
    description: 'Edge deployment model',
    contextWindow: 128000,
    inputCost: 0.02,
    outputCost: 0.3,
    maxOutput: 8192,
    features: ['edge', 'lightweight', 'fast'],
    category: 'fast',
    releaseDate: '2024-09',
    supportsStreaming: true,
  },
  {
    id: 'llama-3.2-1b',
    name: 'Llama 3.2 1B',
    provider: 'Meta',
    icon: '•',
    description: 'Ultra-lightweight edge',
    contextWindow: 128000,
    inputCost: 0.01,
    outputCost: 0.15,
    maxOutput: 8192,
    features: ['edge', 'ultralight', 'fast'],
    category: 'fast',
    releaseDate: '2024-09',
    supportsStreaming: true,
  },
  {
    id: 'llama-3.1-405b',
    name: 'Llama 3.1 405B',
    provider: 'Meta',
    icon: '◉',
    description: 'Large-scale reasoning',
    contextWindow: 128000,
    inputCost: 0.5,
    outputCost: 6,
    maxOutput: 8192,
    features: ['reasoning', 'multilingual', 'large-scale'],
    category: 'flagship',
    releaseDate: '2024-07',
    supportsStreaming: true,
  },
  {
    id: 'llama-3.1-70b',
    name: 'Llama 3.1 70B',
    provider: 'Meta',
    icon: '◊',
    description: 'Balanced performance',
    contextWindow: 128000,
    inputCost: 0.2,
    outputCost: 2.5,
    maxOutput: 8192,
    features: ['general', 'multilingual', 'efficient'],
    category: 'efficient',
    releaseDate: '2024-07',
    supportsStreaming: true,
  },
  {
    id: 'llama-3.1-8b',
    name: 'Llama 3.1 8B',
    provider: 'Meta',
    icon: '○',
    description: 'Lightweight efficient',
    contextWindow: 128000,
    inputCost: 0.05,
    outputCost: 0.6,
    maxOutput: 8192,
    features: ['efficient', 'fast', 'multilingual'],
    category: 'fast',
    releaseDate: '2024-07',
    supportsStreaming: true,
  },

  // ==========================================
  // xAI Grok Family
  // ==========================================
  {
    id: 'grok-4',
    name: 'Grok 4',
    provider: 'xAI',
    icon: '◈',
    description: 'Most intelligent model with tool use',
    contextWindow: 2000000,
    inputCost: 5,
    outputCost: 15,
    maxOutput: 8192,
    features: ['reasoning', 'tools', 'real-time-search', 'web-browsing'],
    category: 'flagship',
    releaseDate: '2025-07',
    supportsStreaming: true,
  },
  {
    id: 'grok-4-0709',
    name: 'Grok 4 (July Snapshot)',
    provider: 'xAI',
    icon: '◈',
    description: 'Specific July 2025 snapshot',
    contextWindow: 2000000,
    inputCost: 5,
    outputCost: 15,
    maxOutput: 8192,
    features: ['reasoning', 'tools', 'real-time-search'],
    category: 'flagship',
    releaseDate: '2025-07',
    supportsStreaming: true,
  },
  {
    id: 'grok-4-fast-reasoning',
    name: 'Grok 4 Fast Reasoning',
    provider: 'xAI',
    icon: '◊',
    description: 'Cost-efficient reasoning',
    contextWindow: 2000000,
    inputCost: 2.5,
    outputCost: 7.5,
    maxOutput: 8192,
    features: ['reasoning', 'efficient', 'fast'],
    category: 'efficient',
    releaseDate: '2025-07',
    supportsStreaming: true,
  },
  {
    id: 'grok-4-fast-non-reasoning',
    name: 'Grok 4 Fast (Non-Reasoning)',
    provider: 'xAI',
    icon: '○',
    description: 'High throughput without thinking',
    contextWindow: 2000000,
    inputCost: 1.5,
    outputCost: 5,
    maxOutput: 8192,
    features: ['fast', 'efficient', 'high-throughput'],
    category: 'fast',
    releaseDate: '2025-07',
    supportsStreaming: true,
  },
  {
    id: 'grok-code-fast-1',
    name: 'Grok Code Fast',
    provider: 'xAI',
    icon: '◐',
    description: 'Specialized for coding',
    contextWindow: 2000000,
    inputCost: 2,
    outputCost: 6,
    maxOutput: 8192,
    features: ['coding', 'fast', 'agentic'],
    category: 'specialized',
    releaseDate: '2025-08',
    supportsStreaming: true,
  },
  {
    id: 'grok-3',
    name: 'Grok 3',
    provider: 'xAI',
    icon: '◉',
    description: 'Prior generation flagship',
    contextWindow: 1000000,
    inputCost: 1,
    outputCost: 3,
    maxOutput: 8192,
    features: ['general', 'stable'],
    category: 'legacy',
    releaseDate: '2025-02',
    supportsStreaming: true,
  },
  {
    id: 'grok-3-mini',
    name: 'Grok 3 Mini',
    provider: 'xAI',
    icon: '○',
    description: 'Efficient Grok 3',
    contextWindow: 500000,
    inputCost: 0.5,
    outputCost: 1.5,
    maxOutput: 8192,
    features: ['efficient', 'fast'],
    category: 'legacy',
    releaseDate: '2025-02',
    supportsStreaming: true,
  },
  {
    id: 'grok-2-vision-1212',
    name: 'Grok 2 Vision',
    provider: 'xAI',
    icon: '◑',
    description: 'Vision-capable language model',
    contextWindow: 128000,
    inputCost: 2,
    outputCost: 6,
    maxOutput: 8192,
    features: ['vision', 'multimodal', 'image-understanding'],
    category: 'specialized',
    releaseDate: '2024-12',
    supportsStreaming: true,
  },
];

// Provider configurations for API integration
export const PROVIDERS = {
  openai: {
    name: 'OpenAI',
    apiKeyEnv: 'OPENAI_API_KEY',
    baseUrl: 'https://api.openai.com/v1',
    info: 'GPT-5.1, GPT-4o, and O-series reasoning models',
    models: AI_MODELS.filter(m => m.provider === 'OpenAI'),
  },
  anthropic: {
    name: 'Anthropic',
    apiKeyEnv: 'ANTHROPIC_API_KEY',
    baseUrl: 'https://api.anthropic.com/v1',
    info: 'Claude Opus 4.1, Sonnet 4.5, and Haiku 4.5',
    models: AI_MODELS.filter(m => m.provider === 'Anthropic'),
  },
  google: {
    name: 'Google',
    apiKeyEnv: 'GOOGLE_API_KEY',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta',
    info: 'Gemini 2.5 Pro, Flash, and Flash-Lite with 1M context',
    models: AI_MODELS.filter(m => m.provider === 'Google'),
  },
  moonshot: {
    name: 'Moonshot',
    apiKeyEnv: 'MOONSHOT_API_KEY',
    baseUrl: 'https://api.moonshot.cn/v1',
    info: 'Kimi K2 with thinking mode and 256K context',
    models: AI_MODELS.filter(m => m.provider === 'Moonshot'),
  },
  deepseek: {
    name: 'DeepSeek',
    apiKeyEnv: 'DEEPSEEK_API_KEY',
    baseUrl: 'https://api.deepseek.com',
    info: 'DeepSeek V3.2 with DeepThink reasoning',
    models: AI_MODELS.filter(m => m.provider === 'DeepSeek'),
  },
  meta: {
    name: 'Meta',
    apiKeyEnv: 'LLAMA_API_KEY',
    baseUrl: 'https://api.llama-api.com/v1',
    info: 'Llama 4 Scout, 3.3, 3.2, and 3.1 models',
    note: 'Available through various cloud providers',
    models: AI_MODELS.filter(m => m.provider === 'Meta'),
  },
  xai: {
    name: 'xAI',
    apiKeyEnv: 'XAI_API_KEY',
    baseUrl: 'https://api.x.ai/v1',
    info: 'Grok 4 with 2M context and real-time search',
    models: AI_MODELS.filter(m => m.provider === 'xAI'),
  },
};

// Group models by category for UI display
export const MODEL_CATEGORIES = {
  flagship: {
    name: 'Flagship Models',
    description: 'Most capable models for complex tasks',
    models: AI_MODELS.filter(m => m.category === 'flagship'),
  },
  reasoning: {
    name: 'Reasoning Models',
    description: 'Advanced chain-of-thought and verification',
    models: AI_MODELS.filter(m => m.category === 'reasoning'),
  },
  efficient: {
    name: 'Balanced Performance',
    description: 'Best balance of capability and cost',
    models: AI_MODELS.filter(m => m.category === 'efficient'),
  },
  fast: {
    name: 'Fast & Lightweight',
    description: 'Optimized for speed and edge deployment',
    models: AI_MODELS.filter(m => m.category === 'fast'),
  },
  specialized: {
    name: 'Specialized Models',
    description: 'Optimized for specific tasks',
    models: AI_MODELS.filter(m => m.category === 'specialized'),
  },
  legacy: {
    name: 'Legacy Models',
    description: 'Older but still available models',
    models: AI_MODELS.filter(m => m.category === 'legacy'),
  },
};

// Helper function to get model by ID
export const getModelById = (id: string): AIModel | undefined => {
  return AI_MODELS.find(model => model.id === id);
};

// Helper function to get models by provider
export const getModelsByProvider = (provider: string): AIModel[] => {
  return AI_MODELS.filter(model => model.provider === provider);
};

// Helper function to get models by category
export const getModelsByCategory = (): Record<string, AIModel[]> => {
  const categories: Record<string, AIModel[]> = {};

  AI_MODELS.forEach(model => {
    const category = model.category || 'other';
    if (!categories[category]) {
      categories[category] = [];
    }
    categories[category].push(model);
  });

  return categories;
};

// Helper function to get models in a specific category
export const getCategoryModels = (category: string): AIModel[] => {
  return AI_MODELS.filter(model => model.category === category);
};

// Helper function to get provider models
export const getProviderModels = (provider: string): AIModel[] => {
  return AI_MODELS.filter(model =>
    model.provider.toLowerCase() === provider.toLowerCase()
  );
};

// Default selected models for initial state
export const DEFAULT_SELECTED_MODELS = [
  'gpt-5.1',
  'claude-sonnet-4-5',
  'gemini-2.5-flash',
  'deepseek-reasoner',
  'grok-4',
];

// Runtime model registry for syncing with provider endpoints
export interface ModelRegistry {
  lastSynced: Date;
  providerModels: Record<string, string[]>;
  customMappings: Record<string, string>;
}

// Function to sync models with provider endpoints at runtime
export const syncModelsWithProviders = async (): Promise<ModelRegistry> => {
  const registry: ModelRegistry = {
    lastSynced: new Date(),
    providerModels: {},
    customMappings: {},
  };

  // This will be implemented to call each provider's /models endpoint
  // and update the registry with available models
  return registry;
};